package com.development.georgemcl.eliminationdietapp.objects

object FoodList {
    val foods: List<Food> = listOf(
        Food("Acidophilus milk, commercial", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Agar-agar (gelatin made from seaweed)",FoodAllowed.Avoid, FoodGroup.Miscellaneous, "A thickener, among other things."),
        Food("Agave syrup", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Algae", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Aggravates an already disturbed immune system."),
        Food("Allspice", FoodAllowed.Allowed, FoodGroup.Spices, "As long as you're just using Allspice as a cooking spice, it's allowed. Don't use the oil."),
        Food("Almond butter", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Almond butter w/ no added sugar"),
        Food("Almond milk, home made", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "<= 8 oz daily if consuming almond baked goods. May be tried after being on diet for 6 months."),
        Food("Almond oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Almonds", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
        Food("Aloe vera", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "It contains mucilaginous polysaccharides."),
        Food("Amaranth flour", FoodAllowed.Avoid, FoodGroup.Starch,"A grain substitute that contains starches."),
        Food("Anchovies", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Check label"),
        Food("Apple cider", FoodAllowed.Allowed, FoodGroup.Drinks, "From a local grower - w/o sugars. Cider should be diluted with water before drinking."),
        Food("Apple juice", FoodAllowed.Avoid, FoodGroup.Drinks, "Poor labeling - unlisted sugars"),
        Food("Apples", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Apricots", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Arrowroot", FoodAllowed.Avoid, FoodGroup.Starch, "It is a mucilaginous herb."),
        Food("Artichoke", FoodAllowed.Allowed, FoodGroup.Vegetables, "French - not jerusalem which looks like a tuber"),
        Food("Ascorbic acid (vitamin C)", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Should be nothing but vitamin C"),
        Food("Asiago cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Asparagus", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Aspartame", FoodAllowed.Allowed, FoodGroup.Sweeteners, "Bad stuff - don't use it anyways"),
        Food("Aspartic acid", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "An amino acid"),
        Food("Astragalus", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Avocado oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Good for mayonnaise and salad dressings but might not withstand  heat very well"),
        Food("Avocados", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Bacon", FoodAllowed.Warning, FoodGroup.AnimalProteins, "Commercial smoked bacon that has been fried very crisply is allowed once per week. Sugar-free bacons do not have to be limited to once per week. Check the labels carefully."),
        Food("Baker's yeast", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Aka: Saccharamyces cerevisae. In brewing, AKA \"Top-fermenting yeast and sometimes \"Ale yeast\"."),
        Food("Baking powder", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Has starch as an ingredient,  (usually corn starch) and other illegals to make it rise better."),
        Food("Baking soda",FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Balsamic vinegar", FoodAllowed.Warning, FoodGroup.Miscellaneous,"Cheap versions are imitation and illegal. Authentic balsamic vinegar is at least 18 years old and quite expensive, but legal. You can make your own - see www.scdrecipe.com."),
        Food("Bananas", FoodAllowed.Allowed, FoodGroup.Fruit, "Ripe with black spots beginning to appear on skin - no green ends"),
        Food("Bark tea", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Acts as a laxative."),
        Food("Barley", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Basil",FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Bay leaf",FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Bean flour", FoodAllowed.Avoid,	FoodGroup.Legumes, "Must be soaked before grinding - bought varieties are not."),
        Food("Bean sprouts", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Bee pollen", FoodAllowed.Avoid,	FoodGroup.Miscellaneous, "Pollen is irritating  to a damaged gut."),
        Food("Beef", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Beer", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Beets", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Berries of all kinds", FoodAllowed.Allowed, FoodGroup.Fruit, "Including blueberries"),
        Food("Bhindi", FoodAllowed.Avoid,	FoodGroup.Vegetables,"A mucilaginous food. Aka: okra,  drumsticks"),
        Food("Bitter gourd", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Black azuki bean", FoodAllowed.Avoid, FoodGroup.Legumes,"Aka: black adzuki, black aduki, asuki"),
        Food("Black beans - aka: black turtle, turtle, turtle soup bean, mexican black bean, spanish black bean, frijole negro.", FoodAllowed.Allowed, FoodGroup.Legumes,	"May be tried when symptom free. see prep guidelines in BTVC book"),
        Food("Black eye beans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Black radish", FoodAllowed.Allowed, FoodGroup.Vegetables,"It is very fibrous, so go slowly and be careful."),
        Food("Blue cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"Occasionally - not shredded / grated"),
        Food("Boiled chestnuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds,"Mixes not allowed"),
        Food("Bok choy", FoodAllowed.Allowed, FoodGroup.Vegetables,"Introduce late in diet."),
        Food("Bologna", FoodAllowed.Avoid, FoodGroup.AnimalProteins),
        Food("Bouillon cubes", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Bourbon", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Brazil nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Mixes not allowed"),
        Food("Brick cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Brie cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"Occasionally - not shredded / grated"),
        Food("Broccoli", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Brussels sprouts", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Buckwheat", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Bulgur", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Burdock root", FoodAllowed.Avoid, FoodGroup.Vegetables,"It contains inulin (FOS) and mucilage."),
        Food("Butter", FoodAllowed.Allowed, FoodGroup.Dairy, "Cultured & grass-fed highly recommended"),
        Food("Butter beans", FoodAllowed.Warning, FoodGroup.Legumes, "See notes on lima and fava (faba) beans"),
        Food("Buttermilk, commercial", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Cabbage", FoodAllowed.Allowed, FoodGroup.Vegetables,"Introduce later in diet."),
        Food("Camembert cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Canellini beans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Canned fish", FoodAllowed.Allowed, FoodGroup.AnimalProteins,"Canned in oil or water, but no broth"),
        Food("Canola oil", FoodAllowed.Avoid, FoodGroup.FatsAndOils, "Highly processed and inflammatory oil."),
        Food("Cantaloupe", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Capers", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Carob", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Carrageenan", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Carrageenan is seaweed and high in polysaccharides, therefore avoid"),
        Food("Carrots", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Catsup, home made", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Cauliflower", FoodAllowed.Allowed, FoodGroup.Vegetables,"Introduce later in diet."),
        Food("Celeriac aka: celery root", FoodAllowed.Allowed, FoodGroup.Vegetables,"Very fibrous, Introduce late in diet."),
        Food("Celery", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Cellulose (in supplements)", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Cellulose in your supplements is okay and virtually impossible to avoid."),
        Food("Cellulose gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Cereals", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Chana dal (dhal, dahl, daal, daar)", FoodAllowed.Avoid,	FoodGroup.Legumes,"aka: chickpea, ceci bean, bengal gram, hummus, chana, channa"),
        Food("Chard (red, green, rainbow, swiss)",FoodAllowed.Allowed, FoodGroup.Vegetables, "Similar to spinach/celery. Introduce late in diet."),
        Food("Cheddar cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"Freely - not shredded / grated"),
        Food("Cherimoya", FoodAllowed.Allowed, FoodGroup.Fruit, "aka: custard apple or sharifa."),
        Food("Cherries", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Chestnut flour", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds,"Store bought is illegal. Nuts must be soaked like beans before making into flour."),
        Food("Chestnuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds,"May be tried when symptom free. However, if you buy dried chestnuts, soak them and cook them until soft."),
        Food("Chevre cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Chewing gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Chia seeds a.k.a silvia seeds, silvia hispanica", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds,"Mucilaginous"),
        Food("Chick peas", FoodAllowed.Avoid, FoodGroup.Legumes,"aka: garbanzo beans, ceci bean, bengal gram, hummus, chana, channa"),
        Food("Chickory root", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Chlorella", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"It is a blue-green  algae similar to spirulina"),
        Food("Chocolate", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Cilantro", FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Cinnamon",FoodAllowed.Allowed, FoodGroup.Spices),
        Food("Citric acid", FoodAllowed.Allowed, FoodGroup.Miscellaneous,"Citric acid as and additive is okay"),
        Food("Club soda", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Cocoa", FoodAllowed.Avoid),
        Food("Coconut", FoodAllowed.Allowed, FoodGroup.Fruit,"Fresh or unsweetened. Shredded and flour are FoodAllowed.Allowed"),
        Food("Coconut flour",	FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Coconut milk", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Home made"),
        Food("Coconut oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Coffee substitutes", FoodAllowed.Avoid,	FoodGroup.Drinks,"Most have malt added"),
        Food("Coffee, instant", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Coffee, very weak", FoodAllowed.Allowed, FoodGroup.Drinks),
        Food("Colby cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Collard greens", FoodAllowed.Allowed, FoodGroup.Vegetables,"Of the cabbage family, introduce late in diet."),
        Food("Corn", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Corn oil", FoodAllowed.Warning, FoodGroup.FatsAndOils, "Highly processed and inflammatory oil. Allowed on SCD, but not on GAPS."),
        Food("Corn syrup", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Cornstarch", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Cottage cheese, regular",FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Courgette / zucchini", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Cranberry juice", FoodAllowed.Allowed, FoodGroup.Drinks,"Knudsen’s Just Cranberry juice, has been checked out FoodAllowed.Allowed. Juice should be diluted with water before drinking."),
        Food("Cream", FoodAllowed.Avoid,FoodGroup.Dairy, "But can be used in making 24hr yoghurt"),
        Food("Cream cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Cream of tartar", FoodAllowed.Avoid),
        Food("Croscarmellose sodium", FoodAllowed.Avoid),
        Food("Cucumbers", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Custard apple", FoodAllowed.Allowed, FoodGroup.Fruit, "aka: sharifa or cherimoya"),
        Food("Cyclamate", FoodAllowed.Allowed, FoodGroup.Sweeteners,"Better alternative than saccharine, because it has no aftertaste. Was suspected of cancer in 1966."),
        Food("Date sugar", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Dates", FoodAllowed.Allowed, FoodGroup.Fruit, "Only loose california or Medjool dates - no sticky dates as these are sweetened"),
        Food("Decaffeinated products", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Process may introduce illegals"),
        Food("Dextrose", FoodAllowed.Avoid, FoodGroup.Sweeteners, "Although a monosaccharide, they are often packaged with other sugars that aren't on the label"),
        Food("Diet soft drink, any other sweetener", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Diet soft drink, aspartame or Nutra-Sweet", FoodAllowed.Warning, FoodGroup.Drinks,"Should be avoided if possible as may contain lactose. Otherwise 1 per week"),
        Food("Diet soft drink, saccharin", FoodAllowed.Warning, FoodGroup.Drinks, "Allowed 2-3 a week on SCD, avoid on GAPS"),
        Food("Dill pickles", FoodAllowed.Allowed,FoodGroup.Vegetables,"W/o added sugars, etc."),
        Food("Dried milk solids", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Drumsticks", FoodAllowed.Avoid, FoodGroup.Vegetables,"aka: okra, bhindi"),
        Food("Dry curd cottage cheese",FoodAllowed.Allowed, FoodGroup.Dairy),
        Food("Durum flour", FoodAllowed.Avoid, FoodGroup.Grains,"It's a wheat flour"),
        Food("Echinacea", FoodAllowed.Allowed, FoodGroup.Miscellaneous,"Especially if it is in Alcohol, but even it is in pill form with a bit of lactose. It can be very helpful if a cold or flu is coming on."),
        Food("Edam cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Eggplant", FoodAllowed.Allowed, FoodGroup.NightshadeVegetables),
        Food("Eggs", FoodAllowed.Allowed, FoodGroup.AnimalProteins),
        Food("Elemental spices", FoodAllowed.Allowed, FoodGroup.Spices,"Cinnamon, nutmeg, etc"),
        Food("Enzyme treated milk", FoodAllowed.Avoid, FoodGroup.Dairy,"Except as noted in book, ch 9"),
        Food("Ethanol", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "aka: alcohol -the kind in gin, etc."),
        Food("Ethanol", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Evaporated cane juice", FoodAllowed.Avoid, FoodGroup.Sweeteners, "aka: sugar"),
        Food("Ezekiel bread", FoodAllowed.Avoid, FoodGroup.Grains,"Sprouted grain breads are illegal"),
        Food("Faba (fava) beans", FoodAllowed.Avoid, FoodGroup.Legumes, "aka: broad bean, fava, horse bean, field bean, tic, Windsor, English, fool, foul, ful, feve, haba, habas and butter bean. See note on lima beans for additional confusion."),
        Food("Fenugreek", FoodAllowed.Avoid, FoodGroup.Herbs),
        Food("Feta cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Figs", FoodAllowed.Allowed, FoodGroup.Fruit, "Can be difficult to digest & laxative"),
        Food("Filberts aka: hazelnuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Mixes not allowed"),
        Food("Fish", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Flax seed", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds),
        Food("Flax seed oil", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "In small amounts"),
        Food("Flour", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Fluid milk of any kind", FoodAllowed.Avoid,	FoodGroup.Dairy, "But can be used in making yoghurt"),
        Food("Food glaze", FoodAllowed.Avoid,	FoodGroup.Miscellaneous, "Found in supplements"),
        Food("FOS (fructooligosaccharides)", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Fowl", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "all types including turkey, chicken, duck, goose, pheasant, pigeon, etc. Fresh and frozen. Check the labels carefully for additives."),
        Food("Frozen concentrated orange juice", FoodAllowed.Avoid,FoodGroup.Drinks, "Concentrating makes it illegal"),
        Food("Fructooligosaccharides (FOS)", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "See BTVC book"),
        Food("Fructose (granulated or liquid)", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "although a monosaccharide, they are often packaged with other sugars that aren't on the label"),
        Food("Fruits, canned", FoodAllowed.Warning, FoodGroup.Fruit, "Allowed only if own juice"),
        Food("Garbanzo beans", FoodAllowed.Avoid,	FoodGroup.Legumes,"aka: chickpea, ceci bean, bengal gram, hummus, chana, channa"),
        Food("Garfava flour", FoodAllowed.Avoid, FoodGroup.Legumes,"Made from garbanzo and fava (faba) beans"),
        Food("Garlic", FoodAllowed.Allowed, FoodGroup.Vegetables, "Fresh - powders have starches"),
        Food("Garlic powder", FoodAllowed.Avoid, FoodGroup.Vegetables, "Starch base - make home made"),
        Food("Gelatin (unflavored)", FoodAllowed.Allowed, FoodGroup.AnimalProteins),
        Food("Ghee", FoodAllowed.Allowed, FoodGroup.Dairy,"aka: clarified butter. Highly reccomended when introducing dairy."),
        Food("Gin", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Ginger", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Gjetost cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Glucose", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "although a monosaccharide, they are often packaged with other sugars that aren't on the label"),
        Food("Glucose candy", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Glycerin", FoodAllowed.Allowed, FoodGroup.Additives, "Widely used additive for food, cosmetics, etc."),
        Food("Glycerol", FoodAllowed.Allowed, FoodGroup.Additives,"Widely used additive for food, cosmetics, etc."),
        Food("Goatein", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "a protein powder"),
        Food("Gorgonzola cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Gouda cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Grape juice, white or dark", FoodAllowed.Allowed, FoodGroup.Drinks,"Not frozen. Welch's purple and white best."),
        Food("Grapefruit", FoodAllowed.Allowed,FoodGroup.Fruit, "Fresh"),
        Food("Grapefruit juice", FoodAllowed.Allowed, FoodGroup.Drinks, "Fresh only. Frozen or canned not allowed. Dilute to drink"),
        Food("Grapes", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Grapeseed oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Highly processed and inflammatory oil. Allowed on SCD, but not on GAPS."),
        Food("Great northern bean", FoodAllowed.Avoid, FoodGroup.Legumes, "aka: cannellini, white kidney, fazolia"),
        Food("Green bean", FoodAllowed.Allowed, FoodGroup.Vegetables, "aka: string bean"),
        Food("Gruyere cheese", FoodAllowed.Allowed,FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Guar gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Gums", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "all gums are illegal"),
        Food("Ham", FoodAllowed.Warning, FoodGroup.AnimalProteins, "Only if cured with salt and legal sweeteners. Check label or get custom smoked."),
        Food("Hard liquor: gin, rye, scotch, bourbon, vodka, etc", FoodAllowed.Warning, FoodGroup.Drinks, "Occasionally"),
        Food("Haricot beans", FoodAllowed.Allowed, FoodGroup.Legumes, "aka: navy bean, white"),
        Food("Havarti cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Hazelnuts (filberts)",FoodAllowed.Allowed, FoodGroup.NutsAndSeeds),
        Food("Hemp seed, hemp protein powder", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds),
        Food("Honey", FoodAllowed.Allowed, FoodGroup.Sweeteners,"Preferably clear, commercial or local. Avoid cloudy as contains pollen."),
        Food("Horseradish sauce", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "If home made or trusted bought"),
        Food("Hot dogs, commercial", FoodAllowed.Avoid, FoodGroup.AnimalProteins, "Unless home made"),
        Food("Hydrolyzed protein aka: MSG", FoodAllowed.Avoid, FoodGroup.Additives),
        Food("Ice cream", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Inositol", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Only small amount in supplements are okay"),
        Food("Instant soup mixes / bases", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Inulin", FoodAllowed.Avoid,	FoodGroup.Starch,"Inulin is a FOS"),
        Food("Iron supplements", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Isoglucose", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Jaggery aka: gur", FoodAllowed.Avoid, FoodGroup.Sweeteners, "an unrefined sugar"),
        Food("Jalapenos", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Jicama", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Juice boxes", FoodAllowed.Avoid, FoodGroup.Drinks, "Regardless of ingredients"),
        Food("Juice from concentrate (any)", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Kala chana - small chickpea w/ brown skin", FoodAllowed.Avoid, FoodGroup.Legumes,"aka: chickpea, ceci bean, bengal gram, hummus, chana, channa"),
        Food("Kale", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Kefir", FoodAllowed.Allowed, FoodGroup.Dairy, "Not recommended early on. See BTVC site. Consider introducing 24hr yoghurt first."),
        Food("Ketchup, commercial", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Ketchup, home made",FoodAllowed.Allowed, FoodGroup.NightshadeVegetables),
        Food("Kidney beans - aka: red bean, rajma dal", FoodAllowed.Allowed, FoodGroup.Legumes),
        Food("Kimchi", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Kiwi", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Kohlrabi", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Kudzu (or kuzu)", FoodAllowed.Avoid,FoodGroup.Miscellaneous, "It's a mucilaginous herb"),
        Food("Kumquats", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("L-leucine aka: leucine", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("L-Theanine", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Lactaid milk", FoodAllowed.Avoid, FoodGroup.Dairy, "aka: lactose hydrolyzed milk"),
        Food("Lamb", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Lecithin", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Leek", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Lemons",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Lentil flour", FoodAllowed.Avoid,	FoodGroup.Legumes, "Must be soaked before grinding - bought varieties are not."),
        Food("Lentils - aka: lens, masoor", FoodAllowed.Allowed, FoodGroup.Legumes, "See prep guidelines in book"),
        Food("Lettuce of all kinds", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Licorice", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Both a demulcent & laxative"),
        Food("Lignin", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Lima beans - fresh or dried.", FoodAllowed.Allowed, FoodGroup.Legumes, "aka: madagascar, wax, butter beans - but be careful as favas (illegal) can be called \"Butter beans\" as well."),
        Food("Limburger cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Limes",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Liquid clorychlorophyll", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Macadamia nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds),
        Food("Macadamia oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Makes great mayo, says Deb"),
        Food("Magnesium citrate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "as a supplement ingredient"),
        Food("Magnesium stearate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "as a supplement ingredient"),
        Food("Malitol", FoodAllowed.Avoid, FoodGroup.Sweeteners, "Sorbitol, mannitol and xylitol are all sugar alcohols"),
        Food("Maltodextrin", FoodAllowed.Avoid, FoodGroup.Additives),
        Food("Manchego cheese", FoodAllowed.Allowed, FoodGroup.Dairy),
        Food("Mangoes", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Mannitol", FoodAllowed.Avoid, FoodGroup.Sweeteners,"Sorbitol, mannitol and xylitol are all sugar alcohols"),
        Food("Maple syrup", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Margarine", FoodAllowed.Avoid, FoodGroup.FatsAndOils, "Milk solids, whey"),
        Food("Marshmallow root", FoodAllowed.Avoid, FoodGroup.Herbs,	"A mucilaginous herb"),
        Food("Masoor dal (dhal, dahl, daal, daar)", FoodAllowed.Allowed, FoodGroup.Legumes, "aka: red lentil"),
        Food("Mastic gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Mead - home made", FoodAllowed.Allowed, FoodGroup.Drinks, "Not commercial"),
        Food("Meats - canned", FoodAllowed.Avoid, FoodGroup.AnimalProteins),
        Food("Meats - processed", FoodAllowed.Avoid, FoodGroup.AnimalProteins),
        Food("Melatonin", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Melons - all types",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Methyl cellulose", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Microcrystalline cellulose", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Millet", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Miso", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Mixed nuts", FoodAllowed.Avoid,	FoodGroup.NutsAndSeeds, "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
        Food("Molasses", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Montery Jack cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Mozzarella cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("MSG - aka: hydrolyzed protein", FoodAllowed.Avoid, FoodGroup.Additives),
        Food("Mucilaginous herbs", FoodAllowed.Avoid, FoodGroup.Herbs),
        Food("Mucilaginous polysaccharides", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Muenster cheese", FoodAllowed.Allowed, FoodGroup.Dairy,	"Occasionally - not shredded / grated"),
        Food("Mung bean", FoodAllowed.Avoid, FoodGroup.Legumes, "aka: mung dal, mash bean, munggo, monggo, green gram, golden gram, green soy"),
        Food("Mung dal (dhal, dahl, daal, daar)", FoodAllowed.Avoid, FoodGroup.Legumes, "aka: mung bean, mash bean, munggo, monggo, green gram, golden gram, green soy"),
        Food("Mushrooms", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Mustard, plain", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Not gourmet - read label"),
        Food("Natural cheeses", FoodAllowed.Allowed, 	FoodGroup.Dairy, "See specific varieties for more"),
        Food("Natural flavors", FoodAllowed.Avoid, FoodGroup.Additives, "Natural flavoring can be used to refer to anything."),
        Food("Navy beans - aka: white, haricot, yankee, white pea bean, boston, small white bean, fagioli", FoodAllowed.Allowed, FoodGroup.Legumes, "See prep guidelines in book"),
        Food("Nectarines", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Nettles", FoodAllowed.Avoid, FoodGroup.Herbs),
        Food("Neufchatel cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Noni juice", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Nutmeg", FoodAllowed.Allowed, FoodGroup.Spices),
        Food("Nuts in mixtures", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds, "Have added starch"),
        Food("Oats", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Okra", FoodAllowed.Avoid, FoodGroup.Vegetables,	"aka: bhindi, drumsticks"),
        Food("Olive oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Highly recommended"),
        Food("Olives", FoodAllowed.Allowed, FoodGroup.Fruit,	"W/o added sugars, etc."),
        Food("Onion powder", FoodAllowed.Avoid, FoodGroup.Spices, "Starch base - make home made"),
        Food("Onions", FoodAllowed.Allowed, FoodGroup.Vegetables, "Fresh - powders have starches"),
        Food("Orange juice", FoodAllowed.Allowed, FoodGroup.Drinks, "Fresh squeezed - not frozen, but avoid in the a.m. Never from concentrate. Tropicana original has been checked out okay."),
        Food("Oranges", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Oregano",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Papayas", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pappadum", FoodAllowed.Avoid, FoodGroup.Legumes, "They  are an Indian snack made from lentils - they're like  a chip. Also contains rice flour"),
        Food("Paprika", FoodAllowed.Allowed, FoodGroup.Spices),
        Food("Parmesan cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Parsley",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Parsnips", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Passion fruit",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pasta, all kinds", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Pau d'arco", FoodAllowed.Avoid, FoodGroup.Drinks,	"aka: bark tea"),
        Food("Pea flour", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Peaches", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Peanut butter, natural", FoodAllowed.Allowed, FoodGroup.Legumes, "Without additives of any kind"),
        Food("Peanut oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Pears",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Peas", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Pecans", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Mixes not allowed"),
        Food("Pectin", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Peppers / capsicum", FoodAllowed.Allowed, FoodGroup.NightshadeVegetables,"Green, yellow, red, jalapeno, habanera, chili, poblano, relleno, etc."),
        Food("Persimmons", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pickels, dill", FoodAllowed.Allowed, FoodGroup.Vegetables, "Check label or make your own"),
        Food("Pignoli / pine nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Hard to digest"),
        Food("Pineapple juice", FoodAllowed.Allowed, FoodGroup.Drinks,"Canned, frozen or fresh w/o sugar"),
        Food("Pineapples",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pinto beans", FoodAllowed.Avoid, FoodGroup.Legumes, "Even with soaking, has wrong kind of starch"),
        Food("Pistachio nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Not roasted  salted as they tend to have starch. Buy raw, unsalted and roast at home."),
        Food("Plant cellulose", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Plantains", FoodAllowed.Avoid,	FoodGroup.Miscellaneous, "Too much starch"),
        Food("Plums",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pomegranate concentrate", FoodAllowed.Avoid, FoodGroup.Fruit),
        Food("Pork", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Pork rinds", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Check label - plain w/ no added flavorings"),
        Food("Port du salut cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Port wine", FoodAllowed.Avoid, FoodGroup.Drinks, "Full of sugar"),
        Food("Postum", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Potassium sorbate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Supplement ingredient"),
        Food("Potatoes of all kinds", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Poultry", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Primost cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Processed cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Protein powder", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Provolone cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "No indication of how often"),
        Food("Prunes", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Psyllium husks - aka: ispaghula", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Main ingredient in many laxatives"),
        Food("Pumpkin", FoodAllowed.Allowed, FoodGroup.Vegetables, "Fresh - not canned"),
        Food("Quinoa", FoodAllowed.Avoid,	FoodGroup.Grains, "a seed"),
        Food("Raisins", FoodAllowed.Allowed, FoodGroup.Fruit, "Preferably dark"),
        Food("Rajma dal (dhal, dahl, daal, daar)", FoodAllowed.Allowed, FoodGroup.Legumes,"aka: kidney bean, red bean"),
        Food("Raw cashews", FoodAllowed.Allowed, FoodGroup.Fruit, "Mixes not allowed"),
        Food("Rhubarb", FoodAllowed.Allowed, FoodGroup.Vegetables, "Can be laxative"),
        Food("Rice - white or brown", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Rice bran", FoodAllowed.Avoid, FoodGroup.Grains, "Unless unavoidable in a supplement"),
        Food("Rice flour", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Ricotta cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Roasted peanuts in the shell", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Shelled / mixes are illegal"),
        Food("Romano cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Roquefort cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Rosemary", FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Rutabaga", FoodAllowed.Allowed, FoodGroup.Vegetables,	"aka: swede - very fiberous, go easy"),
        Food("Rye (the drink)", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Rye (the grain)", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Saccharin",	FoodAllowed.Allowed, FoodGroup.Sweeteners),
        Food("Safflower oil",	FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Sage",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Sago starch", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Sake", FoodAllowed.Avoid, FoodGroup.Drinks, "Not distilled and therefore contains sugars"),
        Food("Salt", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Sashimi", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Plain, w/o rice etc."),
        Food("Sauerkraut", FoodAllowed.Allowed, FoodGroup.Vegetables,  "Only for advanced SCD'ers"),
        Food("Scotch", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Seaweed", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Seed butters", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "In very limited amounts - see web"),
        Food("Seeds", FoodAllowed.Allowed,FoodGroup.NutsAndSeeds, "Allowed only 3 months after last symptom has disappeared"),
        Food("Sesame oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Sesame seeds", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Okay after 3 months of no symptoms"),
        Food("Sharifa", FoodAllowed.Allowed, FoodGroup.Fruit, "aka: custard apple, cherimoya"),
        Food("Shellfish", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Sherry, cordials, liqueurs or brandy", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Silica", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Silica silicon dioxide", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Silvia seed a.k.a., silvia hispanica, chia seeds", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds, "Mucilaginous"),
        Food("Slippery elm", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Mucilaginous"),
        Food("Smoked meats", FoodAllowed.Warning, FoodGroup.AnimalProteins, "Unless you are certain of ingredients - i.e. you know the smoker or make your own."),
        Food("Sodium benzoate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Supplement ingredient"),
        Food("Sodium starch glycinate", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Sorbitol", FoodAllowed.Avoid, FoodGroup.Sweeteners,	"Sorbitol, mannitol and xylitol are all sugar alcohols"),
        Food("Sour cream, commercial", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Soy", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Soy lecithin", FoodAllowed.Avoid, FoodGroup.Additives),
        Food("Soy sauce / tamari", FoodAllowed.Avoid,	FoodGroup.Legumes),
        Food("Soybean milk", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Soybean oil", FoodAllowed.Avoid, FoodGroup.FatsAndOils, "Highly processed and inflammatory oil."),
        Food("Soybeans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Sparkling water a.k.a. seltzer water", FoodAllowed.Allowed, FoodGroup.Drinks, "Ingredients: only carbonated water"),
        Food("Spelt", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Spice mixes", FoodAllowed.Avoid, FoodGroup.Spices, "Most contain starches"),
        Food("Spinach", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Spirulina", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Splenda", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Split peas", FoodAllowed.Allowed, FoodGroup.Vegetables, "See prep guidelines in book"),
        Food("Sports drinks", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Sprouted grain bread", FoodAllowed.Avoid, FoodGroup.Grains, "Ezekiel bread, for instance"),
        Food("Squash", FoodAllowed.Allowed, FoodGroup.Vegetables, "Summer and winter"),
        Food("Starches of any kind", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Stevia", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Stilton cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("String beans", FoodAllowed.Allowed, FoodGroup.Vegetables, "aka: green bean"),
        Food("Sucralose", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Sugar", FoodAllowed.Avoid,	FoodGroup.Sweeteners, "aka: table sugar, white sugar, refined sugar, evaporated cane juice."),
        Food("Sulphates", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Used on fruits to prevent discoloring"),
        Food("Sunflower oil",	FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Swede - aka: rutabaga", FoodAllowed.Allowed, FoodGroup.Vegetables, "Very fibrous, go easy"),
        Food("Sweet potato - aka: yam", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Swiss cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Tabasco sauce", FoodAllowed.Allowed, FoodGroup.Miscellaneous,"Only the original red Tabasco sauce, labeled 'McIlhenny Company Tabasco Brand Pepper Sauce' is allowed but check the label."),
        Food("Tagatose", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Tahini - aka: sesame seed butter", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Okay after 3 months of no symptoms"),
        Food("Tamari", FoodAllowed.Warning, FoodGroup.Sauces, "Better than regular soy sauce. Make sure it's wheat free. After 3 months of no symptoms."),
        Food("Tamarind", FoodAllowed.Avoid, FoodGroup.Fruit),
        Food("Tangerines",FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Tapioca", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Tapioca flour", FoodAllowed.Avoid, FoodGroup.Starch, "Found in supplements"),
        Food("Tapioca starch", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Taro", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Tarragon",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Tea, green", FoodAllowed.Allowed, FoodGroup.Drinks, "Limited to 2 cups / day"),
        Food("Tea, instant", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Tea, peppermint", FoodAllowed.Allowed, FoodGroup.Drinks, "Read label"),
        Food("Tea, spearmint",	FoodAllowed.Allowed, FoodGroup.Drinks),
        Food("Tea, weak", FoodAllowed.Allowed, FoodGroup.Drinks,	"Ordinary black tea is allowed but should be made weak. Instant tea, Ojibwa tea (Essiac), many herbal teas, teas made from bark etc., are illegal. Peppermint and spearmint herb teas are allowed, as well as home made ginger tea."),
        Food("Teas, herbal", FoodAllowed.Avoid, FoodGroup.Drinks, "Tend to be laxative"),
        Food("Thyme",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Tofu", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Tofutti cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Tomato juice", FoodAllowed.Allowed, FoodGroup.Drinks, "Only salt added. No V-8."),
        Food("Tomato juice mixtures", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Tomato paste, canned", FoodAllowed.Avoid, FoodGroup.NightshadeVegetables),
        Food("Tomato puree, canned", FoodAllowed.Avoid, FoodGroup.NightshadeVegetables),
        Food("Tomato sauce, canned", FoodAllowed.Avoid, FoodGroup.NightshadeVegetables),
        Food("Tomatoes",	FoodAllowed.Allowed, FoodGroup.NightshadeVegetables),
        Food("Triticale", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Turbinado", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Turnips", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Uncreamed cottage cheese / dry curd cottage cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Unflavored gelatin", FoodAllowed.Allowed, FoodGroup.AnimalProteins),
        Food("V8 juice", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Val dal (dhal, dahl, daal, daar)", FoodAllowed.Avoid, FoodGroup.Legumes, "aka: split lab beans, bonavist, Egyptian, Fugi mame, India bean, hyacinth, field, avarekai, fava"),
        Food("Vanillin", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "But not in pure form"),
        Food("Vegetable cellulose", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Vegetable stearate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "a vegetable fat"),
        Food("Vegetables, canned", FoodAllowed.Avoid, FoodGroup.Vegetables, "None - must be fresh or frozen"),
        Food("Vinegar, apple cider", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Not gourmet as these have added sugars. Must be filtered."),
        Food("Vinegar, red or white wine", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Not gourmet as these have added sugars"),
        Food("Vinegar, white", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Not gourmet as these have added sugars"),
        Food("Vodka", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Walnut oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Doesn't withstand heat well"),
        Food("Walnuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Mixes not allowed"),
        Food("Wasabi", FoodAllowed.Allowed, FoodGroup.Spices, "W/o additives or fillers"),
        Food("Water chestnuts", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds),
        Food("Watercress", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Watermelon", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Wheat", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Wheat germ", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("White kidney bean", FoodAllowed.Avoid, FoodGroup.Legumes, "aka: cannellini, great northern, fazolia"),
        Food("Wine, very dry ", FoodAllowed.Allowed, FoodGroup.Drinks),
        Food("Xanthum gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Xylitol", FoodAllowed.Avoid, FoodGroup.Sweeteners, "Sorbitol, mannitol and xylitol are all sugar alcohols"),
        Food("Yam - aka: sweet potato", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Yoghurt, commercial", FoodAllowed.Avoid, FoodGroup.Dairy, "Except as a starter for home made yoghurt. Danon plain is good. Check label."),
        Food("Yoghurt, home made", FoodAllowed.Allowed, FoodGroup.Dairy, "Processed at least 24 hrs. Milk and cream are okay. Cow or goat."),
        Food("Yucca root", FoodAllowed.Avoid, FoodGroup.Miscellaneous))
}

