package com.development.georgemcl.eliminationdietapp.objects

object FoodList {
    val foods: List<Food> = listOf(
        Food("acidophilus milk, commercial", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("agar-agar (gelatin made from seaweed)",FoodAllowed.Avoid, FoodGroup.Miscellaneous, "a thickener, among other things."),
        Food("agave syrup", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("algae", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "aggravates an already disturbed immune system."),
        Food("allspice", FoodAllowed.Allowed, FoodGroup.Spices, "As long as you're just using Allspice as a cooking spice, it's allowed. Don't use the oil."),
        Food("almond butter", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "almond butter w/ no added sugar"),
        Food("almond milk, home made", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "<= 8 oz daily if consuming almond baked goods. May be tried after being on diet for 6 months."),
        Food("almond oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("almonds", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
        Food("aloe vera", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "It contains mucilaginous polysaccharides."),
        Food("amaranth flour", FoodAllowed.Avoid, FoodGroup.Starch,"A grain substitute that contains starches."),
        Food("anchovies", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "check label"),
        Food("apple cider", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "from a local grower - w/o sugars. Cider should be diluted with water before drinking."),
        Food("apple juice", FoodAllowed.Avoid, FoodGroup.Fruit, "poor labeling - unlisted sugars"),
        Food("apples", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("apricots", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("arrowroot", FoodAllowed.Avoid, FoodGroup.Starch, "It is a mucilaginous herb."),
        Food("artichoke", FoodAllowed.Allowed, FoodGroup.Vegetables, "french - not jerusalem which looks like a tuber"),
        Food("ascorbic acid (vitamin C)", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "should be nothing but vitamin C"),
        Food("asiago cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "occasionally - not shredded / grated"),
        Food("asparagus", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("aspartame", FoodAllowed.Allowed, FoodGroup.Sweeteners, "bad stuff - don't use it anyways"),
        Food("aspartic acid", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "an amino acid"),
        Food("astragalus", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("avocado oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Good for mayonnaise and salad dressings but might not withstand  heat very well"),
        Food("avocados", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("bacon", FoodAllowed.Warning, FoodGroup.AnimalProteins, "Commercial smoked bacon that has been fried very crisply is allowed once per week. Sugar-free bacons do not have to be limited to once per week. Check the labels carefully."),
        Food("baker's yeast", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"aka: Saccharamyces cerevisae. In brewing, AKA \"top-fermenting yeast and sometimes \"ale yeast\"."),
        Food("baking powder", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Has starch as an ingredient,  (usually corn starch) and other illegals to make it rise better."),
        Food("baking soda",FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("balsamic vinegar", FoodAllowed.Warning, FoodGroup.Miscellaneous,"Cheap versions are imitation and illegal. Authentic balsamic vinegar is at least 18 years old and quite expensive, but legal. You can make your own - see www.scdrecipe.com."),
        Food("bananas", FoodAllowed.Allowed, FoodGroup.Fruit, "Ripe with black spots beginning to appear on skin - no green ends"),
        Food("bark tea", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "acts as a laxative."),
        Food("barley", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("basil",FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("bay leaf",FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("bean flour", FoodAllowed.Avoid,	FoodGroup.Legumes, "must be soaked before grinding - bought varieties are not."),
        Food("bean sprouts", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("bee pollen", FoodAllowed.Avoid,	FoodGroup.Miscellaneous, "Pollen is irritating  to a damaged gut."),
        Food("beef", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("beer", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("beets", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("berries of all kinds", FoodAllowed.Allowed, FoodGroup.Fruit, "including blueberries"),
        Food("bhindi", FoodAllowed.Avoid,	FoodGroup.Vegetables,"A mucilaginous food. Aka: okra,  drumsticks"),
        Food("bitter gourd", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("black azuki bean", FoodAllowed.Avoid, FoodGroup.Legumes,"aka: black adzuki, black aduki, asuki"),
        Food("black beans - aka: black turtle, turtle, turtle soup bean, mexican black bean, spanish black bean, frijole negro.", FoodAllowed.Allowed, FoodGroup.Legumes,	"May be tried when symptom free. see prep guidelines in BTVC book"),
        Food("black eye beans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("black radish", FoodAllowed.Allowed, FoodGroup.Vegetables,"It is very fibrous, so go slowly and be careful."),
        Food("blue cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"occasionally - not shredded / grated"),
        Food("boiled chestnuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds,"mixes not allowed"),
        Food("bok choy", FoodAllowed.Allowed, FoodGroup.Vegetables,"Introduce late in diet."),
        Food("bologna", FoodAllowed.Avoid, FoodGroup.AnimalProteins),
        Food("bouillon cubes", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("bourbon", FoodAllowed.Allowed, FoodGroup.Drinks, "occasionally"),
        Food("brazil nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "mixes not allowed"),
        Food("brick cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "freely - not shredded / grated"),
        Food("brie cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"occasionally - not shredded / grated"),
        Food("broccoli", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("brussels sprouts", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("buckwheat", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("bulgur", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("burdock root", FoodAllowed.Avoid, FoodGroup.Vegetables,"It contains inulin (FOS) and mucilage."),
        Food("butter", FoodAllowed.Allowed, FoodGroup.Dairy, "cultured & grass-fed highly recommended"),
        Food("butter beans", FoodAllowed.Warning, FoodGroup.Legumes, "see notes on lima and fava (faba) beans"),
        Food("buttermilk, commercial", FoodAllowed.Avoid, FoodGroup.Dairy))
}

