package com.development.georgemcl.scdgapsapp.objects

object AIPFoodList {
    /**
     * From https://healingautoimmune.com/aip-food-list
     */
    val foods: List<Food> = listOf(

        /**
         * ALLOWED
         */

        Food("Artichoke", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Arugula/Rocket", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Asparagus", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Beets", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Broccoli", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Brussels sprouts", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Bok choy", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Cabbage", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Carrots", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Cauliflower", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Chard", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Cucumber", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Fennel", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Jicama", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Kale", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Leek", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Lettuce", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Mushroom", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Onion", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Parsnip", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Rutabaga", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Spinach", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Sweet potato", FoodAllowed.ALLOWED, FoodGroup.Starch),

        Food("Acorn squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Artichoke hearts", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Butternut squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Cassava", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Celery", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Chinese cabbage", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Chicory", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Collard greens", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Endive", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Fiddleheads", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Green onions", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Jerusalem artichokes", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Kohlrabi", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Mustard greens", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Okra", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Parsley", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Pumpkin", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Radicchio", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Radish", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Rapini", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Romaine lettuce", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Seaweed", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Spaghetti squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Spring onions", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Swiss chard", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Taro", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Turnips", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Turnip greens", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Watercress", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Yellow crookneck", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Yellow squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Yam", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Zucchini", FoodAllowed.ALLOWED, FoodGroup.Vegetables),


        Food("Apple", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Apricot", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Banana", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Berries", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Cherry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Coconut", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Date", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Fig", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Grapes", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Kiwi", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Mango", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Melons", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Peach", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Pear", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Persimmon", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Plum", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Pineapple", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Pomegranate", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Watermelon", FoodAllowed.ALLOWED, FoodGroup.Fruit),

        Food("Grapefruit", FoodAllowed.ALLOWED, FoodGroup.Fruit),

        Food("Blackberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Blueberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Cranberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Raspberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Olive", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Avocado", FoodAllowed.ALLOWED, FoodGroup.Fruit),

        Food("Cantaloupe", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Guava", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Honeydew", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Lemon", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Lime", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Lychee", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Nectarine", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Orange", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Papaya", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Passion Fruit", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Star Fruit", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Strawberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Tangerine", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Rhubarb", FoodAllowed.ALLOWED, FoodGroup.Fruit),


        Food("Basil", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Bay leaf", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Chives", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Cilantro", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Cinnamon", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Dill", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Ginger", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Garlic", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Mint", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Peppermint", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Rosemary", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Saffron", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Sage", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Thyme", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Turmeric", FoodAllowed.ALLOWED, FoodGroup.Herbs),

        Food("Dandelion", FoodAllowed.ALLOWED, FoodGroup.Herbs),

        Food("Lemon balm", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Chamomile", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Chervil", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Cloves", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Horseradish", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Lavender", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Mace", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Marjoram", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Oregano", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Spearmint", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Tarragon", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Lemongrass", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Wasabi", FoodAllowed.ALLOWED, FoodGroup.Herbs),


        Food("Beef", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Bison", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Chicken", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Duck", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Fish", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Lamb", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Shellfish", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Pork", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Bacon", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Turkey", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Venison", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),

        Food("Elk", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),

        Food("Goat", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Goose", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Kangaroo", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Veal", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Organ meats", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins, "Highly recommended"),

        Food("Anchovies", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Bass", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Cod", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Eel", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Mackerel", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Sardines", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Tuna", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Oysters", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Lobster", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Mussels", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Shrimp", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),

        Food("Avocado oil", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Tallow", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Chicken fat", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Coconut oil", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Olive oil", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Palm oil", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),

        Food("Lard", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Duck Fat", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),


//        Food("Apple cider vinegar", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Arrowroot starch", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Carob powder", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Cassava flour", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Coconut flour", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Dried fruit", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Honey", FoodAllowed.Warning, FoodGroup.Sweeteners, "Okay in moderation"),
        Food("Tapioca starch", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Tigernut flour", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),

        Food("Cocoa", FoodAllowed.NOT_ALLOWED, FoodGroup.Miscellaneous, "Stage 1 reintroduction Food"),
        Food("Chocolate", FoodAllowed.NOT_ALLOWED, FoodGroup.Miscellaneous, "Stage 1 reintroduction Food"),

        Food("Coffee", FoodAllowed.NOT_ALLOWED, FoodGroup.Drinks, "Small quantities - stage 1 reintroduction food.\nDaily basis - stage 2 reintroduction food."),
        Food("Tea (herbal, green, black)", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Balsamic vinegar", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Apple cider vinegar", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Coconut water vinegar", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Red / white wine vinegar", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Vinegar", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Coconut aminos", FoodAllowed.ALLOWED, FoodGroup.Sauces),
        Food("Fish sauce", FoodAllowed.ALLOWED, FoodGroup.Sauces),
        Food("Capers", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Gelatin", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Coconut water", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut milk kefir", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut milk (no emulsifiers)", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut cream", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),

        Food("Kvass", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Arrowroot powder", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Baking soda", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Green banana flour", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Cream of tartar", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Kuzu starch", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Water chestnut flour", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Plantain flour", FoodAllowed.ALLOWED, FoodGroup.Starch),


        Food("Water kefir", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut yogurt", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Sauerkraut", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Kombucha", FoodAllowed.ALLOWED, FoodGroup.Drinks, "Make sure you buy or make ones with live cultures and without additives or extra sugar"),


        /**
         * NOT aLLOWED
         */


        Food("Amaranth", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Barley", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Buckwheat", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Bulger", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Corn", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Millet", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Oats", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Quinoa", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("White rice", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains, "Stage 4 reintroduction Food"),
        Food("Brown rice", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Rye", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Sorghum", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Spelt", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Wheat", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),

        Food("Pasta", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Bread", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Crackers", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),

        Food("Butter", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy, "Stage 2 reintroduction Food (grass-fed)"),
        Food("Cheese", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),
        Food("Cream", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),
        Food("Ghee", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy, "Stage 1 reintroduction Food"),
        Food("Milk", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),
        Food("Yogurt", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),

        Food("Sour cream", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),
        Food("Kefir", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),

        Food("Black beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Chickpeas", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Fava beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Kidney beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Lentils", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Lima beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Peanut", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Soybeans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),

        Food("Garbanzo beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Mung beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Snow peas", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Sugar snap peas", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Tofu", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Soy milk", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("White beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Pinto beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Red beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),


        Food("Eggplant / aubergine", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Goji berries", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Ground cherry", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Peppers (all)", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Red spices (all)", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Potato", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables, "Peeled - stage 3 reintroduction food. Unpeeled - stage 4 reintroduction food."),
        Food("Tomato", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables, "Stage 4 reintroduction food."),
        Food("Tomatillo", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),



        Food("Ashwagandha", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Capsicum", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Cocona", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Garden huckleberries", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Kutjera", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Naranjillas", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Pepinos", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Pimentos", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Cape gooseberries", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),

        Food("Almond", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Brazil nut", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Canola", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Cashew", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Chestnuts", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Chia seeds", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Flax seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Hazelnut", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Macadamias", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Pecan", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Pine nuts", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Pistachio", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Pumpkin seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Safflower seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Sesame seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Sunflower seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Walnut", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),

        Food("Allspice", FoodAllowed.ALLOWED, FoodGroup.Spices),
        Food("Anise", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),

        Food("Caraway", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Celery seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Cumin", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Fennel seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Mustard seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Nutmeg", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Pepper", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Poppy seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),

        Food("Annatto seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Black caraway", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Coriander seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Dill seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Fenugreek", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),

        Food("Cayenne pepper", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Paprika", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Red pepper Flakes", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Chili pepper Flakes", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Curry powder", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Garam masala", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Chinese five-Spice powder", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Steak seasoning", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),

        Food("Eggs", FoodAllowed.NOT_ALLOWED, FoodGroup.AnimalProteins, "Egg yolks are a stage 1 reintroduction food and egg whites are a stage 2 reintroduction food."),

        Food("Alcohol", FoodAllowed.NOT_ALLOWED, FoodGroup.Drinks),

        Food("Sugar", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Coconut sugar", FoodAllowed.Warning, FoodGroup.Sweeteners, "Okay in moderation"),
        Food("Maple syrup", FoodAllowed.Warning, FoodGroup.Sweeteners, "Okay in moderation"),

        Food("High fructose corn syrup", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Artificial sweeteners", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Agave", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Maltodextrin", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Corn syrup", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Molasses", FoodAllowed.Warning, FoodGroup.Sweeteners, "Okay in moderation"),
        Food("Pomegranate molasses", FoodAllowed.Warning, FoodGroup.Sweeteners, "Okay in moderation"),
        Food("Date sugar", FoodAllowed.Warning, FoodGroup.Sweeteners, "Okay in moderation"),

        Food("Rice syrup", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Soda", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Candy", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Stevia", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),

        Food("Corn oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Canola oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Vegetable oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Soybean oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Sunflower oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Safflower oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Cottonseed oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Grapeseed oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Peanut oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Palm kernel oil", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Shortening", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils),
        Food("Margarine", FoodAllowed.NOT_ALLOWED, FoodGroup.FatsAndOils)

    )
}