package com.development.georgemcl.scdgapsapp.objects

object AIPFoodList {
    /**
     * From https://healingautoimmune.com/aip-food-list
     */
    val foods: List<Food> = listOf(

        /**
         * ALLOWED
         */

        Food("Artichoke", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Arugula/Rocket", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Asparagus", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Beets", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Broccoli", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Brussels Sprouts", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Bok Choy", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Cabbage", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Carrots", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Cauliflower", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Chard", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Cucumber", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Fennel", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Jicama", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Kale", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Leek", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Lettuce", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Mushroom", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Onion", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Parsnip", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Rutabaga", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Spinach", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Sweet potato", FoodAllowed.ALLOWED, FoodGroup.Vegetables),

        Food("Acorn Squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Artichoke Hearts", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Avocado", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Butternut Squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Cassava", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Celery", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Chinese Cabbage", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Chicory", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Collard Greens", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Endive", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Fiddleheads", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Green Onions", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Jerusalem Artichokes", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Kohlrabi", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Mustard Greens", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Okra", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Parsley", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Pumpkin", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Radicchio", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Radish", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Rapini", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Romaine Lettuce", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Radicchio", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Seaweed", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Spaghetti Squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Swiss Chard", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Taro", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Turnips", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Turnip Greens", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Watercress", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Yellow Crookneck", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Yellow Squash", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Yam", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Zucchini", FoodAllowed.ALLOWED, FoodGroup.Vegetables),


        Food("Apple", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Apricot", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Banana", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Berries", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Cherry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Citrus", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Coconut", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Date", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Fig", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Grapes", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Kiwi", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Mango", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Melons", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Peach", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Pear", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Persimmon", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Plum", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Pineapple", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Pomegranate", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Watermelon", FoodAllowed.ALLOWED, FoodGroup.Fruit),

        Food("Blackberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Blueberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Cranberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Raspberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Olive", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Avocado", FoodAllowed.ALLOWED, FoodGroup.Fruit),

        Food("Cantaloupe", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Avocado", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Guava", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Honeydew", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Lemon", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Lime", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Lychee", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Nectarines", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Oranges", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Papaya", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Passion Fruit", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Rhubarb", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Star Fruit", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Strawberry", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Tangerine", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Rhubarb", FoodAllowed.ALLOWED, FoodGroup.Fruit),


        Food("Basil", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Bay leaf", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Chives", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Cilantro", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Cinnamon", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Dill", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Ginger", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Garlic", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Mint", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Parsley", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Peppermint", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Rosemary", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Saffron", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Sage", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Thyme", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Turmeric", FoodAllowed.ALLOWED, FoodGroup.Herbs),

        Food("Lemon balm", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Chamomile", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Chervil", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Chives", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Cloves", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Horseradish", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Lavender", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Mace", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Marjoram", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Oregano", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Spearmint", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Tarragon", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Lemongrass", FoodAllowed.ALLOWED, FoodGroup.Herbs),
        Food("Wasabi", FoodAllowed.ALLOWED, FoodGroup.Herbs),


        Food("Beef", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Bison", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Chicken", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Duck", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Fish", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Lamb", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Shellfish", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Pork", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Turkey", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Venison", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),

        Food("Elk", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),

        Food("Goat", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Goose", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Kangaroo", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Veal", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Organ Meats", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins, "Highly reccomended"),

        Food("Anchovies", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Bass", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Cod", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Eel", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Mackerel", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Sardines", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Tuna", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Oysters", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Lobster", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Mussels", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Shrimp", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),

        Food("Avocado oil", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Tallow", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Chicken fat", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Coconut oil", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Olive oil", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Palm oil", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),

        Food("Lard", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),
        Food("Duck Fat", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),


//        Food("Apple cider vinegar", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Arrowroot starch", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Carob powder", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Cassava flour", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Coconut flour", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Dried fruit", FoodAllowed.ALLOWED, FoodGroup.Fruit),
        Food("Honey", FoodAllowed.ALLOWED, FoodGroup.Sweeteners),
        Food("Tapioca starch", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Tigernut flour", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),

        Food("Cocoa", FoodAllowed.Warning, FoodGroup.Miscellaneous),
        Food("Coffee", FoodAllowed.Warning, FoodGroup.Drinks),
        Food("Tea (herbal, green, black)", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Vinegars (apple cider, coconut water vinegar, red wine, white wine, balsamic)", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Coconut aminos", FoodAllowed.ALLOWED, FoodGroup.Sauces),
        Food("Fish Sauce", FoodAllowed.ALLOWED, FoodGroup.Sauces),
        Food("Capers", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Gelatin", FoodAllowed.ALLOWED, FoodGroup.AnimalProteins),
        Food("Coconut Water", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut Milk Kefir", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut Milk (no emulsifiers)", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut Cream", FoodAllowed.ALLOWED, FoodGroup.FatsAndOils),

        Food("Kvass", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Arrowroot powder", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Baking Soda", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Carob Powder", FoodAllowed.ALLOWED, FoodGroup.Legumes),
        Food("Green Banana Flour", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Cream of Tartar", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Kuzu Starch", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Water Chestnut Flour", FoodAllowed.ALLOWED, FoodGroup.Starch),
        Food("Plantain Flour", FoodAllowed.ALLOWED, FoodGroup.Starch),


        Food("Water kefir", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut kefir", FoodAllowed.ALLOWED, FoodGroup.Drinks),
        Food("Coconut yogurt", FoodAllowed.ALLOWED, FoodGroup.Miscellaneous),
        Food("Sauerkraut", FoodAllowed.ALLOWED, FoodGroup.Vegetables),
        Food("Kombucha", FoodAllowed.ALLOWED, FoodGroup.Drinks, "Make sure you buy or make ones with live cultures and without additives or extra sugar"),




        /**
         * NOT ALLOWED
         */


        Food("Amaranth", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Barley", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Buckwheat", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Bulger", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Corn", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Millet", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Oats", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Quinoa", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("White rice", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains, "Stage 4 Reintroduction Food"),
        Food("Brown rice", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Millet", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Oats", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Quinoa", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Rice", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Rye", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Sorghum", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Spelt", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),
        Food("Wheat", FoodAllowed.NOT_ALLOWED, FoodGroup.Grains),

        Food("Butter", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),
        Food("Cheese", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),
        Food("Cream", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),
        Food("Ghee", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy, "Stage 4 Reintroduction Food"),
        Food("Milk", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),
        Food("Yogurt", FoodAllowed.NOT_ALLOWED, FoodGroup.Dairy),

        Food("Black beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Chickpeas", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Cocoa", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Fava beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Kidney beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Lentils", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Lima beans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Peanut", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),
        Food("Soybeans", FoodAllowed.NOT_ALLOWED, FoodGroup.Legumes),

        Food("Eggplant", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Goji berries", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Ground cherry", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Peppers (all)", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Red spices (all)", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Potato", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Tomato", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),
        Food("Tomatillo", FoodAllowed.NOT_ALLOWED, FoodGroup.NightshadeVegetables),

        Food("Almond", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Brazil nut", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Canola", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Cashew", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Chia", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Coffee", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Cocoa", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Flax seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Hazelnut", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Pecan", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Pine nuts", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Pistachio", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Pumpkin seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Safflower seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Sesame seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Sunflower seed", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),
        Food("Walnut", FoodAllowed.NOT_ALLOWED, FoodGroup.NutsAndSeeds),

        Food("Allspice", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Anise", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Caraway", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Celery seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Cumin", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Fennel seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Mustard", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Nutmeg", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Pepper", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),
        Food("Poppy seed", FoodAllowed.NOT_ALLOWED, FoodGroup.Spices),


        Food("Eggs", FoodAllowed.NOT_ALLOWED, FoodGroup.AnimalProteins),

        Food("Alcohol", FoodAllowed.NOT_ALLOWED, FoodGroup.Drinks),

        Food("Sugar", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Coconut Sugar", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners),
        Food("Maple Syrup", FoodAllowed.NOT_ALLOWED, FoodGroup.Sweeteners)
    )
}