package com.development.georgemcl.scdgapsapp.objects

object FoodList {
    val foods: List<Food> = listOf(
//        Food("Acidophilus milk, commercial", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Agar-agar (gelatin made from seaweed)",FoodAllowed.Avoid, FoodGroup.Miscellaneous, "A thickener, among other things."),
        Food("Agave syrup", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Algae", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Aggravates an already disturbed immune system."),
        Food("Allspice", FoodAllowed.Allowed, FoodGroup.Spices, "As long as you're just using Allspice as a cooking spice, it's allowed. Don't use the oil."),
        Food("Almond butter", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Ensure no added sugar"),
        Food("Almond milk, home made", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "May be tried after being on diet for 6 months."),
        Food("Almond oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Almonds", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating. Nuts should only be used as nut flour, in recipes, until diarrhea has subsided."),
        Food("Aloe vera", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "It contains mucilaginous polysaccharides as well as increasing the release of tumor necrosis factor which is associated with IBD inflammation and increased immune stimulation."),
        Food("Amaranth flour", FoodAllowed.Avoid, FoodGroup.Starch,"A grain substitute that contains starches."),
        Food("Anchovies", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Check label"),
        Food("Apple cider", FoodAllowed.Allowed, FoodGroup.Drinks, "It is brown and not clear as apple juice is. It should be just straight pressed apples. It is usually pasteurized in order to kill bacteria. Cider should be diluted with water before drinking."),
        Food("Apple juice", FoodAllowed.Avoid, FoodGroup.Drinks, "Apple juice usually has sugar added during processing. Apple cider is allowed. It should be brown and not clear as apple juice is. Cider should be diluted with water before drinking."),
        Food("Apples", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Apricots", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Arrowroot", FoodAllowed.Avoid, FoodGroup.Starch, "It is a mucilaginous herb loaded with starch."),
        Food("Artichoke (French)", FoodAllowed.Allowed, FoodGroup.Vegetables, "They are the green artichokes that you steam, then dip the leaves in lemon butter and scrape off with your teeth. They have edible hearts and an inedible choke."),
        Food("Artichokes (Jerusalem)", FoodAllowed.Avoid, FoodGroup.Vegetables, "They are actually a tuber, and are not legal."),
        Food("Ascorbic acid (vitamin C)", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Should be nothing but vitamin C."),
        Food("Asiago cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "May be used occasionally."),
        Food("Asparagus", FoodAllowed.Allowed, FoodGroup.Vegetables, "Fresh or frozen is allowed. Canned vegetables are not allowed."),
        Food("Aspartame", FoodAllowed.Avoid, FoodGroup.Sweeteners, "SCD allows 1 aspartame sweetened drink per week when symptom free. It is a neurotoxin, so best to avoid."),
        Food("Aspartic acid", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Astragalus", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Avocado oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Avocados", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Bacon", FoodAllowed.Warning, FoodGroup.AnimalProteins, "Smoked bacon that has been fried very crisply is allowed once per week. There are sugar-free bacons available and if you are able to find a source of sugar-free bacon, you do not have to limit your consumption to once per week. Usually the low sodium varieties do not contain sugar but check the labels carefully."),
        Food("Baker's yeast", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Saccharamyces cerevisae is baker's yeast and is illegal."),
        Food("Baking powder", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Has starch as an ingredient, (usually corn starch) and other illegals to make it rise better."),
        Food("Baking soda",FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Balsamic vinegar", FoodAllowed.Warning, FoodGroup.Miscellaneous,"It's not that balsamic vinegar is illegal, it's that what you can get in the store isn't really balsamic vinegar and most have sugar added to them so Elaine doesn't allow it. You can make your own legal substitute though see scdrecipe"),
        Food("Bananas", FoodAllowed.Allowed, FoodGroup.Fruit, "They must be ripe with black spots on the skin."),
        Food("Bark tea", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Bark tea (Pau d'Arco) contains steroidal saponins and is both an immune booster and a laxative."),
        Food("Barley", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Basil",FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Bay leaf",FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Bean flour", FoodAllowed.Avoid, FoodGroup.Legumes, "Do not use ready made flours made from beans or lentils as they probably weren't soaked prior to grinding to bean flour."),
        Food("Bean sprouts", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Bee pollen", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Pollen is irritating to a damaged gut. Clear, pure, pasteurized honey is okay. Cloudy honey (still containing the pollen) should be avoided."),
        Food("Beef", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen are allowed as long as nothing has been added during processing; check the labels carefully."),
        Food("Beer", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Beets", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Berries of all kinds", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Bhindi", FoodAllowed.Avoid, FoodGroup.Vegetables,"No okra (bhindi) or drumsticks, since they are a mucilaginous food, they are illegal."),
        Food("Bitter gourd", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Black azuki bean", FoodAllowed.Avoid, FoodGroup.Legumes,"Aka: black adzuki, black aduki, asuki"),
        Food("Black beans", FoodAllowed.Allowed, FoodGroup.Legumes,	"May be tried when symptom free. Dried legumes must be prepared according to the instructions in the Breaking the Vicious Cycle book."),
        Food("Black eye beans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Black radish", FoodAllowed.Allowed, FoodGroup.Vegetables,"It is very fibrous, so go slowly and be careful."),
        Food("Blue cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"May be used occasionally."),
        Food("Bok choy", FoodAllowed.Allowed, FoodGroup.Vegetables,"Bok Choy is much like cabbage and is legal but you should not use a member of the cabbage family until you are well on your way to getting better. In other words, do not use if you still have diarrhea and gas."),
        Food("Bologna", FoodAllowed.Avoid, FoodGroup.AnimalProteins),
        Food("Bouillon cubes", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Bouillon cubes and instant soup bases are not permitted."),
        Food("Bourbon", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Brandy", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Brazil nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
        Food("Brick cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "May be used freely."),
        Food("Brie cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"May be used occasionally."),
        Food("Broccoli", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Brussels sprouts", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Buckwheat", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Bulgur", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Burdock root", FoodAllowed.Avoid, FoodGroup.Vegetables,"It contains inulin (FOS) and mucilage."),
        Food("Butter", FoodAllowed.Allowed, FoodGroup.Dairy),
        Food("Butter beans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Buttermilk, commercial", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Butternut squash", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Cabbage", FoodAllowed.Allowed, FoodGroup.Vegetables,"You should not use a member of the cabbage family until you are well on your way to getting better. In other words, do not use if you still have diarrhea and gas."),
        Food("Camembert cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "May be used occasionally."),
        Food("Canellini beans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Canned fish", FoodAllowed.Allowed, FoodGroup.AnimalProteins,"Canned in oil or water is acceptable but check the labels carefully. Do not buy products containing \"broth\". Usually, the low sodium varieties do not contain \"broth\"."),
        Food("Canned fruits", FoodAllowed.Avoid, FoodGroup.FatsAndOils, "Fruits canned in their own juice are allowed."),
        Food("Canner vegetables", FoodAllowed.Avoid, FoodGroup.FatsAndOils, "There are no canned vegetables permitted, they must either be fresh or frozen."),
        Food("Canola oil", FoodAllowed.Warning, FoodGroup.FatsAndOils, "Legal, but not recommended. Highly processed and inflammatory oil."),
        Food("Cantaloupe", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Capers", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Carob", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Carrageenan", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Carrageenan is seaweed and high in polysaccharides, therefore illegal."),
        Food("Carrots", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Cashews", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
        Food("Cauliflower", FoodAllowed.Allowed, FoodGroup.Vegetables,"Cauliflower is sometimes hard to digest and should be tried cautiously after some progress has been made on the diet."),
        Food("Celeriac aka: celery root", FoodAllowed.Allowed, FoodGroup.Vegetables,"However, you should go slow and be careful. It is very fibrous, even if it doesn't seem so when you steam it and mash it."),
        Food("Celery", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Cellulose (in supplements)", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Cellulose in your supplements is okay and virtually impossible to avoid."),
        Food("Cellulose gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Cereals", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Chard (red, green, rainbow, swiss)", FoodAllowed.Allowed, FoodGroup.Vegetables, "Similar to spinach/celery. Introduce late in diet."),
        Food("Cheddar cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"May be used freely."),
        Food("Cheese", FoodAllowed.Allowed, FoodGroup.Dairy,"If a cheese is not a processed cheese (manufactured) but is a cheese that has had a bacterial culture involved with its production and is aged at least 30 days."),
        Food("Cherimoya", FoodAllowed.Allowed, FoodGroup.Fruit, "Aka: custard apple or sharifa."),
        Food("Cherries", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Chestnut flour", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds),
        Food("Chestnuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds,"May be tried when symptom free. However, if you buy dried chestnuts, soak them and cook them until soft."),
        Food("Chevre cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Chewing gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Chia seeds", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds,"Mucilaginous"),
        Food("Chick peas", FoodAllowed.Avoid, FoodGroup.Legumes, "Chickory root is not legal. In my first book, I suggested that it might be used instead of coffee beans. I have since learned that it contains large amounts of fructooligosaccharides. - Elaine"),
        Food("Chickory root", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Chlorella", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"It is a blue-green algae similar to spirulina"),
        Food("Chocolate", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Dr. Haas advised not to use cocoa or chocolate and this still goes, it isn't just the sugar he was worried about."),
        Food("Cilantro", FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Cinnamon",FoodAllowed.Allowed, FoodGroup.Spices),
        Food("Citric acid", FoodAllowed.Allowed, FoodGroup.Miscellaneous,"Citric acid as and additive is okay"),
        Food("Club soda", FoodAllowed.Allowed, FoodGroup.Drinks),
        Food("Cocoa powder", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Dr. Haas advised not to use cocoa or chocolate and this still goes, it isn't just the sugar he was worried about."),
        Food("Coconut", FoodAllowed.Allowed, FoodGroup.Fruit,"Fresh or unsweetened, shredded and flour are all legal."),
        Food("Coconut milk", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "May be tried after being on the diet for 6 months."),
        Food("Coconut oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Withstands heat well, good for frying/cooking"),
        Food("Coffee (instant)", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Coffee (very weak)", FoodAllowed.Allowed, FoodGroup.Drinks),
        Food("Colby cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "May be used freely."),
        Food("Collard greens", FoodAllowed.Allowed, FoodGroup.Vegetables,"Of the cabbage family, introduce late in diet."),
        Food("Corn", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Corn oil", FoodAllowed.Warning, FoodGroup.FatsAndOils, "Legal, but not recommended. Highly processed and inflammatory oil."),
        Food("Corn syrup", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Cornstarch", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Cottage cheese",FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Courgette / zucchini", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Cranberry juice", FoodAllowed.Allowed, FoodGroup.Drinks,"Knudsen’s Just Cranberry juice is allowed. Juice should be diluted with water before drinking."),
        Food("Cream", FoodAllowed.Avoid,FoodGroup.Dairy, "But can be used in making 24hr yoghurt"),
        Food("Cream cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Cream of tartar", FoodAllowed.Avoid),
        Food("Croscarmellose sodium", FoodAllowed.Avoid),
        Food("Cucumbers", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Custard apple", FoodAllowed.Allowed, FoodGroup.Fruit, "Aka: sharifa or cherimoya"),
        Food("Cyclamate", FoodAllowed.Allowed, FoodGroup.Sweeteners,"Better alternative than saccharine, because it has no aftertaste. Was suspected of cancer in 1966."),
        Food("Date sugar", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Dates", FoodAllowed.Allowed, FoodGroup.Fruit, "Only loose california or Medjool dates - no sticky dates as these are sweetened"),
        Food("Decaffeinated products", FoodAllowed.Avoid, FoodGroup.Miscellaneous,"Process may introduce illegals"),
        Food("Dextrose", FoodAllowed.Avoid, FoodGroup.Sweeteners, "Although a monosaccharide, they are often packaged with other sugars that aren't on the label"),
        Food("Diet soft drink, other sweetneer", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Diet soft drink, saccharin", FoodAllowed.Warning, FoodGroup.Drinks, "Allowed 2-3 a week on SCD, avoid on GAPS"),
        Food("Dill pickles", FoodAllowed.Allowed,FoodGroup.Vegetables,"W/o added sugars, etc."),
        Food("Dried milk solids", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Drumsticks", FoodAllowed.Avoid, FoodGroup.Vegetables,"Aka: okra, bhindi"),
        Food("Dry curd cottage cheese",FoodAllowed.Allowed, FoodGroup.Dairy),
        Food("Durum flour", FoodAllowed.Avoid, FoodGroup.Grains,"It's a wheat flour"),
        Food("Echinacea", FoodAllowed.Allowed, FoodGroup.Miscellaneous,"Especially if it is in Alcohol, but even it is in pill form with a bit of lactose. It can be very helpful if a cold or flu is coming on."),
        Food("Edam cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Eggplant", FoodAllowed.Allowed, FoodGroup.NightshadeVegetables),
        Food("Eggs", FoodAllowed.Allowed, FoodGroup.AnimalProteins),
        Food("Elemental spices", FoodAllowed.Allowed, FoodGroup.Spices,"Cinnamon, nutmeg, etc"),
        Food("Enzyme treated milk", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Ethanol", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Aka: alcohol -the kind in gin, etc."),
        Food("Evaporated cane juice", FoodAllowed.Avoid, FoodGroup.Sweeteners, "Aka: sugar"),
        Food("Ezekiel bread", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Faba beans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Fenugreek", FoodAllowed.Avoid, FoodGroup.Herbs),
        Food("Feta cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Figs", FoodAllowed.Allowed, FoodGroup.Fruit, "Can be difficult to digest & laxative"),
        Food("Filberts aka: hazelnuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Mixes not allowed"),
        Food("Fish", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Flax seed", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds),
        Food("Flax seed oil", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "In small amounts"),
        Food("Flour", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Fluid milk of any kind", FoodAllowed.Avoid,	FoodGroup.Dairy, "But can be used in making yoghurt"),
        Food("Food glaze", FoodAllowed.Avoid,	FoodGroup.Miscellaneous, "Found in supplements"),
        Food("FOS (fructooligosaccharides)", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Fowl", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "All types including turkey, chicken, duck, goose, pheasant, pigeon, etc. Fresh and frozen. Check the labels carefully for additives."),
        Food("Frozen concentrated orange juice", FoodAllowed.Avoid,FoodGroup.Drinks, "Concentrating makes it illegal"),
        Food("Fructooligosaccharides (FOS)", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "See BTVC book"),
        Food("Fructose (granulated or liquid)", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Although a monosaccharide, they are often packaged with other sugars that aren't on the label"),
        Food("Fruits, canned", FoodAllowed.Warning, FoodGroup.Fruit, "Allowed only if own juice"),
        Food("Garbanzo beans", FoodAllowed.Avoid,	FoodGroup.Legumes,"Aka: chickpea, ceci bean, bengal gram, hummus, chana, channa"),
        Food("Garfava flour", FoodAllowed.Avoid, FoodGroup.Legumes,"Made from garbanzo and fava (faba) beans"),
        Food("Garlic", FoodAllowed.Allowed, FoodGroup.Vegetables, "Fresh - powders have starches"),
        Food("Garlic powder", FoodAllowed.Avoid, FoodGroup.Vegetables, "Starch base - make home made"),
        Food("Gelatin (unflavored)", FoodAllowed.Allowed, FoodGroup.AnimalProteins),
        Food("Ghee", FoodAllowed.Allowed, FoodGroup.Dairy,"Aka: clarified butter. Highly recommended when introducing dairy."),
        Food("Gin", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Ginger", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Gjetost cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Glucose", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Although a monosaccharide, they are often packaged with other sugars that aren't on the label"),
        Food("Glucose candy", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Glycerin", FoodAllowed.Allowed, FoodGroup.Additives, "Widely used additive for food, cosmetics, etc."),
        Food("Glycerol", FoodAllowed.Allowed, FoodGroup.Additives,"Widely used additive for food, cosmetics, etc."),
        Food("Goatein", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "A protein powder"),
        Food("Gorgonzola cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Gouda cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Grape juice, white or dark", FoodAllowed.Allowed, FoodGroup.Drinks,"Not frozen. Welch's purple and white best."),
        Food("Grapefruit", FoodAllowed.Allowed,FoodGroup.Fruit, "Fresh"),
        Food("Grapefruit juice", FoodAllowed.Allowed, FoodGroup.Drinks, "Fresh only. Frozen or canned not allowed. Dilute to drink"),
        Food("Grapes", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Grapeseed oil", FoodAllowed.Warning, FoodGroup.FatsAndOils, "Highly processed and inflammatory oil. Allowed on SCD, but not on GAPS."),
        Food("Great northern bean", FoodAllowed.Avoid, FoodGroup.Legumes, "Aka: cannellini, white kidney, fazolia"),
        Food("Green bean", FoodAllowed.Allowed, FoodGroup.Vegetables, "Aka: string bean"),
        Food("Gruyere cheese", FoodAllowed.Allowed,FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Guar gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Gums", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "All gums are illegal"),
        Food("Ham", FoodAllowed.Warning, FoodGroup.AnimalProteins, "Only if cured with salt and legal sweeteners. Check label or get custom smoked."),
        Food("Hard liquor: gin, rye, scotch, bourbon, vodka, etc", FoodAllowed.Warning, FoodGroup.Drinks, "Occasionally"),
        Food("Haricot beans / navy beans", FoodAllowed.Allowed, FoodGroup.Legumes, "Must be prepared correctly."),
        Food("Havarti cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Hazelnuts (filberts)",FoodAllowed.Allowed, FoodGroup.NutsAndSeeds),
        Food("Hemp seed, hemp protein powder", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds),
        Food("Honey", FoodAllowed.Allowed, FoodGroup.Sweeteners,"Preferably clear, commercial or local. Avoid cloudy as contains pollen."),
        Food("Horseradish sauce", FoodAllowed.Allowed, FoodGroup.Sauces, "If home made or trusted bought"),
        Food("Hot dogs, commercial", FoodAllowed.Avoid, FoodGroup.AnimalProteins, "Unless home made"),
        Food("Hydrolyzed protein aka: MSG", FoodAllowed.Avoid, FoodGroup.Additives),
        Food("Ice cream", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Inositol", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Only small amount in supplements are okay"),
        Food("Instant soup mixes / bases", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Inulin", FoodAllowed.Avoid,	FoodGroup.Starch,"Inulin is a FOS"),
        Food("Iron supplements", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Isoglucose", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Jaggery aka: gur", FoodAllowed.Avoid, FoodGroup.Sweeteners, "An unrefined sugar"),
        Food("Jalapenos", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Jicama", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Juice boxes", FoodAllowed.Avoid, FoodGroup.Drinks, "Regardless of ingredients"),
        Food("Juice from concentrate (any)", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Kala chana - small chickpea w/ brown skin", FoodAllowed.Avoid, FoodGroup.Legumes,"Aka: chickpea, ceci bean, bengal gram, hummus, chana, channa"),
        Food("Kale", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Kefir", FoodAllowed.Allowed, FoodGroup.Dairy, "Not recommended early on. See BTVC site. Consider introducing 24hr yoghurt first."),
        Food("Ketchup, commercial", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Ketchup, home made",FoodAllowed.Allowed, FoodGroup.NightshadeVegetables),
        Food("Kidney beans - aka: red bean, rajma dal", FoodAllowed.Warning, FoodGroup.Legumes, "May be tried when symptom free, apply caution. Must be prepared correctly."),
        Food("Kimchi", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Kiwi", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Kohlrabi", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Kudzu (or kuzu)", FoodAllowed.Avoid,FoodGroup.Miscellaneous, "It's a mucilaginous herb"),
        Food("Kumquats", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("L-leucine aka: leucine", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("L-Theanine", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Lactaid milk", FoodAllowed.Avoid, FoodGroup.Dairy, "Aka: lactose hydrolyzed milk"),
        Food("Lamb", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Lecithin", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Leek", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Lemons",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Lentil flour", FoodAllowed.Avoid,	FoodGroup.Legumes, "Must be soaked before grinding - bought varieties are not."),
        Food("Lentils - aka: lens, masoor", FoodAllowed.Allowed, FoodGroup.Legumes, "See prep guidelines in book"),
        Food("Lettuce of all kinds", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Licorice", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Both a demulcent & laxative"),
        Food("Lignin", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Lima beans - fresh or dried.", FoodAllowed.Allowed, FoodGroup.Legumes, "May be tried when symptom free. Must be prepared correctly."),
        Food("Limburger cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Limes",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Liquid clorychlorophyll", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Macadamia nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds),
        Food("Macadamia oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Magnesium citrate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "As a supplement ingredient"),
        Food("Magnesium stearate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "As a supplement ingredient"),
        Food("Malitol", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Maltodextrin", FoodAllowed.Avoid, FoodGroup.Additives),
        Food("Manchego cheese", FoodAllowed.Allowed, FoodGroup.Dairy),
        Food("Mangoes", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Mannitol", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Maple syrup", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Margarine", FoodAllowed.Avoid, FoodGroup.FatsAndOils, "Milk solids, whey"),
        Food("Marshmallow root", FoodAllowed.Avoid, FoodGroup.Herbs,	"A mucilaginous herb"),
        Food("Mastic gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Mead - home made", FoodAllowed.Allowed, FoodGroup.Drinks, "Not commercial"),
        Food("Meats - canned", FoodAllowed.Avoid, FoodGroup.AnimalProteins),
        Food("Meats - processed", FoodAllowed.Avoid, FoodGroup.AnimalProteins),
        Food("Melatonin", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Melons - all types",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Methyl cellulose", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Microcrystalline cellulose", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Millet", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Miso", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Mixed nuts", FoodAllowed.Avoid,	FoodGroup.NutsAndSeeds, "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
        Food("Molasses", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Montery Jack cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Mozzarella cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("MSG - aka: hydrolyzed protein", FoodAllowed.Avoid, FoodGroup.Additives),
        Food("Mucilaginous herbs", FoodAllowed.Avoid, FoodGroup.Herbs),
        Food("Mucilaginous polysaccharides", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Muenster cheese", FoodAllowed.Allowed, FoodGroup.Dairy,	"Occasionally - not shredded / grated"),
        Food("Mung bean", FoodAllowed.Avoid, FoodGroup.Legumes, "Aka: mung dal, mash bean, munggo, monggo, green gram, golden gram, green soy"),
        Food("Mushrooms", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Mustard, plain", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Not gourmet - read label"),
        Food("Natural cheeses", FoodAllowed.Allowed, 	FoodGroup.Dairy, "See specific varieties for more"),
        Food("Natural flavors", FoodAllowed.Avoid, FoodGroup.Additives, "Natural flavoring can be used to refer to anything."),
        Food("Navy beans", FoodAllowed.Allowed, FoodGroup.Legumes, "Must be prepared correctly."),
        Food("Nectarines", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Nettles", FoodAllowed.Avoid, FoodGroup.Herbs),
        Food("Neufchatel cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Noni juice", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Nutmeg", FoodAllowed.Allowed, FoodGroup.Spices),
        Food("Nuts in mixtures", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds, "Have added starch"),
        Food("Oats", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Okra", FoodAllowed.Avoid, FoodGroup.Vegetables,	"Aka: bhindi, drumsticks"),
        Food("Olive oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Highly recommended"),
        Food("Olives", FoodAllowed.Allowed, FoodGroup.Fruit,	"W/o added sugars, etc."),
        Food("Onion powder", FoodAllowed.Avoid, FoodGroup.Spices, "Starch base - make home made"),
        Food("Onions", FoodAllowed.Allowed, FoodGroup.Vegetables, "Fresh - powders have starches"),
        Food("Orange juice", FoodAllowed.Allowed, FoodGroup.Drinks, "Fresh squeezed - not frozen, but avoid in the a.m. Never from concentrate. Tropicana original has been checked out okay."),
        Food("Oranges", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Oregano",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Papayas", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pappadum", FoodAllowed.Avoid, FoodGroup.Legumes, "They are an Indian snack made from lentils - they're like a chip. Also contains rice flour"),
        Food("Paprika", FoodAllowed.Allowed, FoodGroup.Spices),
        Food("Parmesan cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Parsley",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Parsnips", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Passion fruit",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pasta, all kinds", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Pau d'arco", FoodAllowed.Avoid, FoodGroup.Drinks,	"Aka: bark tea"),
        Food("Pea flour", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Peaches", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Peanut butter, natural", FoodAllowed.Allowed, FoodGroup.Legumes, "Without additives of any kind"),
        Food("Peanut oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Pears",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Peas", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Pecans", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Mixes not allowed"),
        Food("Pectin", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Peppers / capsicum", FoodAllowed.Allowed, FoodGroup.NightshadeVegetables,"Green, yellow, red, jalapeno, habanera, chili, poblano, relleno, etc."),
        Food("Persimmons", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pickels, dill", FoodAllowed.Allowed, FoodGroup.Vegetables, "Check label or make your own"),
        Food("Pignoli / pine nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Hard to digest"),
        Food("Pineapple juice", FoodAllowed.Allowed, FoodGroup.Drinks,"Canned, frozen or fresh w/o sugar"),
        Food("Pineapples",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pinto beans", FoodAllowed.Avoid, FoodGroup.Legumes, "Even with soaking, has wrong kind of starch"),
        Food("Pistachio nuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Not roasted salted as they tend to have starch. Buy raw, unsalted and roast at home."),
        Food("Plant cellulose", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Plantains", FoodAllowed.Avoid,	FoodGroup.Miscellaneous, "Too much starch"),
        Food("Plums",	FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Pomegranate concentrate", FoodAllowed.Avoid, FoodGroup.Fruit),
        Food("Pork", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Pork rinds", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Check label - plain w/ no added flavorings"),
        Food("Port du salut cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Port wine", FoodAllowed.Avoid, FoodGroup.Drinks, "Full of sugar"),
        Food("Postum", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Potassium sorbate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Supplement ingredient"),
        Food("Potatoes of all kinds", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Poultry", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Primost cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Processed cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Protein powder", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Provolone cheese", FoodAllowed.Allowed, FoodGroup.Dairy),
        Food("Prunes", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Psyllium husks - aka: ispaghula", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Main ingredient in many laxatives"),
        Food("Pumpkin", FoodAllowed.Allowed, FoodGroup.Vegetables, "Fresh - not canned"),
        Food("Quinoa", FoodAllowed.Avoid,	FoodGroup.Grains),
        Food("Raisins", FoodAllowed.Allowed, FoodGroup.Fruit, "Preferably dark"),
        Food("Raw cashews", FoodAllowed.Allowed, FoodGroup.Fruit, "Mixes not allowed"),
        Food("Rhubarb", FoodAllowed.Allowed, FoodGroup.Vegetables, "Can be laxative"),
        Food("Rice - white or brown", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Rice bran", FoodAllowed.Avoid, FoodGroup.Grains, "Unless unavoidable in a supplement"),
        Food("Rice flour", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Ricotta cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Roasted peanuts in the shell", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Shelled / mixes are illegal"),
        Food("Romano cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Roquefort cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("Rosemary", FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Rutabaga", FoodAllowed.Allowed, FoodGroup.Vegetables,	"Aka: swede - very fiberous, go easy"),
        Food("Rye (the drink)", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Rye (the grain)", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Saccharin",	FoodAllowed.Allowed, FoodGroup.Sweeteners),
        Food("Safflower oil",	FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Sage",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Sago starch", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Sake", FoodAllowed.Avoid, FoodGroup.Drinks, "Not distilled and therefore contains sugars"),
        Food("Salt", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Sashimi", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Plain, w/o rice etc."),
        Food("Sauerkraut", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Sausages, commercial", FoodAllowed.Avoid, FoodGroup.AnimalProteins),
        Food("Scotch", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Seaweed", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Seed butters", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "In very limited amounts"),
        Food("Seeds", FoodAllowed.Allowed,FoodGroup.NutsAndSeeds, "Allowed after 3 months of no symptoms"),
        Food("Sesame oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils),
        Food("Sesame seeds", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Allowed after 3 months of no symptoms"),
        Food("Sharifa", FoodAllowed.Allowed, FoodGroup.Fruit, "Aka: custard apple, cherimoya"),
        Food("Shellfish", FoodAllowed.Allowed, FoodGroup.AnimalProteins, "Fresh and frozen. Check the labels carefully for additives."),
        Food("Sherry, cordials, liqueurs or brandy", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Silica", FoodAllowed.Allowed, FoodGroup.Miscellaneous),
        Food("Silica silicon dioxide", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Silvia seed a.k.a., silvia hispanica, chia seeds", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds, "Mucilaginous"),
        Food("Slippery elm", FoodAllowed.Avoid, FoodGroup.Miscellaneous, "Mucilaginous"),
        Food("Smoked meats", FoodAllowed.Warning, FoodGroup.AnimalProteins, "Unless you are certain of ingredients - i.e. you know the smoker or make your own."),
        Food("Sodium benzoate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Supplement ingredient"),
        Food("Sodium starch glycinate", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Sorbitol", FoodAllowed.Avoid, FoodGroup.Sweeteners,	"Sorbitol, mannitol and xylitol are all sugar alcohols"),
        Food("Sour cream, commercial", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Soy", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Soy lecithin", FoodAllowed.Avoid, FoodGroup.Additives),
        Food("Soy sauce / tamari", FoodAllowed.Avoid,	FoodGroup.Legumes),
        Food("Soybean milk", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Soybean oil", FoodAllowed.Avoid, FoodGroup.FatsAndOils, "Highly processed and inflammatory oil."),
        Food("Soybeans", FoodAllowed.Avoid, FoodGroup.Legumes),
        Food("Sparkling water a.k.a. seltzer water", FoodAllowed.Allowed, FoodGroup.Drinks, "Ingredients: only carbonated water"),
        Food("Spelt", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Spice mixes", FoodAllowed.Avoid, FoodGroup.Spices, "Most contain starches"),
        Food("Spinach", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Spirulina", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Splenda", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Split peas", FoodAllowed.Allowed, FoodGroup.Vegetables, "Must be prepared correctly."),
        Food("Sports drinks", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Sprouted grain bread", FoodAllowed.Avoid, FoodGroup.Grains, "Ezekiel bread, for instance"),
        Food("Squash", FoodAllowed.Allowed, FoodGroup.Vegetables, "Summer and winter"),
        Food("Starches of any kind", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Stevia", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Stilton cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Occasionally - not shredded / grated"),
        Food("String beans / green beans", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Sucralose", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Sugar", FoodAllowed.Avoid,	FoodGroup.Sweeteners, "Aka: table sugar, white sugar, refined sugar, evaporated cane juice."),
        Food("Sulphates", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Used on fruits to prevent discoloring"),
        Food("Sunflower oil",	FoodAllowed.Warning, FoodGroup.FatsAndOils, "Processed and inflammatory oil. Allowed on SCD, but not on GAPS."),
        Food("Swede - aka: rutabaga", FoodAllowed.Allowed, FoodGroup.Vegetables, "Very fibrous, go easy"),
        Food("Sweet potato - aka: yam", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Swiss cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Tabasco sauce", FoodAllowed.Allowed, FoodGroup.Sauces,"Only the original red Tabasco sauce, labeled 'McIlhenny Company Tabasco Brand Pepper Sauce' is allowed but check the label."),
        Food("Tagatose", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Tahini - aka: sesame seed butter", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Allowed after 3 months of no symptoms"),
        Food("Tamari", FoodAllowed.Warning, FoodGroup.Sauces, "Better than regular soy sauce. Make sure it's wheat free. After 3 months of no symptoms."),
        Food("Tamarind", FoodAllowed.Avoid, FoodGroup.Fruit),
        Food("Tangerines",FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Tapioca", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Tapioca flour", FoodAllowed.Avoid, FoodGroup.Starch, "Found in supplements"),
        Food("Tapioca starch", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Taro", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Tarragon",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Tea, green", FoodAllowed.Allowed, FoodGroup.Drinks, "Limited to 2 cups / day"),
        Food("Tea, instant", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Tea, peppermint", FoodAllowed.Allowed, FoodGroup.Drinks, "Read label"),
        Food("Tea, spearmint",	FoodAllowed.Allowed, FoodGroup.Drinks),
        Food("Tea, weak", FoodAllowed.Allowed, FoodGroup.Drinks,	"Ordinary black tea is allowed but should be made weak. Instant tea, Ojibwa tea (Essiac), many herbal teas, teas made from bark etc., are illegal. Peppermint and spearmint herb teas are allowed, as well as home made ginger tea."),
        Food("Teas, herbal", FoodAllowed.Avoid, FoodGroup.Drinks, "Tend to be laxative"),
        Food("Thyme",	FoodAllowed.Allowed, FoodGroup.Herbs),
        Food("Tofu", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Tofutti cheese", FoodAllowed.Avoid, FoodGroup.Dairy),
        Food("Tomato juice", FoodAllowed.Allowed, FoodGroup.Drinks, "Only salt added. No V-8."),
        Food("Tomato juice mixtures", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Tomato paste, canned", FoodAllowed.Avoid, FoodGroup.NightshadeVegetables),
        Food("Tomato puree, canned", FoodAllowed.Avoid, FoodGroup.NightshadeVegetables),
        Food("Tomato sauce, canned", FoodAllowed.Avoid, FoodGroup.Sauces),
        Food("Tomatoes",	FoodAllowed.Allowed, FoodGroup.NightshadeVegetables),
        Food("Triticale", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Turbinado", FoodAllowed.Avoid, FoodGroup.Sweeteners),
        Food("Turnips", FoodAllowed.Avoid, FoodGroup.Vegetables),
        Food("Uncreamed cottage cheese / dry curd cottage cheese", FoodAllowed.Allowed, FoodGroup.Dairy, "Freely - not shredded / grated"),
        Food("Unflavored gelatin", FoodAllowed.Allowed, FoodGroup.AnimalProteins),
        Food("V8 juice", FoodAllowed.Avoid, FoodGroup.Drinks),
        Food("Vanillin", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "But not in pure form"),
        Food("Vegetable cellulose", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Found in supplements"),
        Food("Vegetable stearate", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "A vegetable fat"),
        Food("Vegetables, canned", FoodAllowed.Avoid, FoodGroup.Vegetables, "None - must be fresh or frozen"),
        Food("Vinegar, apple cider", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Not gourmet as these have added sugars. Must be filtered."),
        Food("Vinegar, red or white wine", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Not gourmet as these have added sugars"),
        Food("Vinegar, white", FoodAllowed.Allowed, FoodGroup.Miscellaneous, "Not gourmet as these have added sugars"),
        Food("Vodka", FoodAllowed.Allowed, FoodGroup.Drinks, "Occasionally"),
        Food("Walnut oil", FoodAllowed.Allowed, FoodGroup.FatsAndOils, "Doesn't withstand heat well"),
        Food("Walnuts", FoodAllowed.Allowed, FoodGroup.NutsAndSeeds, "Mixes not allowed"),
        Food("Wasabi", FoodAllowed.Allowed, FoodGroup.Spices, "W/o additives or fillers"),
        Food("Water chestnuts", FoodAllowed.Avoid, FoodGroup.NutsAndSeeds),
        Food("Watercress", FoodAllowed.Allowed, FoodGroup.Vegetables),
        Food("Watermelon", FoodAllowed.Allowed, FoodGroup.Fruit),
        Food("Wheat", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Wheat germ", FoodAllowed.Avoid, FoodGroup.Grains),
        Food("Whey, powder or liquid", FoodAllowed.Avoid, FoodGroup.Dairy, "Avoid on GAPS."),
        Food("White kidney bean", FoodAllowed.Avoid, FoodGroup.Legumes, "Aka: cannellini, great northern, fazolia"),
        Food("Wine, very dry ", FoodAllowed.Allowed, FoodGroup.Drinks),
        Food("Xanthum gum", FoodAllowed.Avoid, FoodGroup.Miscellaneous),
        Food("Xylitol", FoodAllowed.Avoid, FoodGroup.Sweeteners, "Sorbitol, mannitol and xylitol are all sugar alcohols"),
        Food("Yam - aka: sweet potato", FoodAllowed.Avoid, FoodGroup.Starch),
        Food("Yoghurt, commercial", FoodAllowed.Avoid, FoodGroup.Dairy, "Except as a starter for home made yoghurt. Danon plain is good. Check label."),
        Food("Yoghurt, home made", FoodAllowed.Allowed, FoodGroup.Dairy, "Processed at least 24 hrs. Milk and cream are okay. Cow or goat."),
        Food("Yucca root", FoodAllowed.Avoid, FoodGroup.Miscellaneous))
}

